apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hellas
build:
  artifacts:
    - image: ironhalo/hellas
      docker:
        dockerfile: cmd/server/Dockerfile
test:
  - image: ironhalo/hellas
    custom:
      - command: "go test -v ./..."
        dependencies:
          paths:
          - "internal/**"
          - "cmd/**/*.go"
          - "api/**"
          - "models/*.go"
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml
