apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hellas
build:
  artifacts:
  - image: ironhalo/hellas
    docker:
      dockerfile: cmd/server/Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/*.yaml
