apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hellas
build:
  artifacts:
    - image: ironhalo/hellas
      docker:
        dockerfile: cmd/server/Dockerfile
test:
  - image: ironhalo/hellas
    custom:
      - command: "go test -v ./..."
        dependencies:
          paths:
          - "./**/*.go"
deploy:
  helm:
    releases:
      - name: hellas
        chartPath: charts/hellas
        artifactOverrides:
          imageKey: ironhalo/hellas
        imageStrategy:
          helm: {}
