apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  config.json: |-
    {
    {{- if .Values.moduleRegistryType }}
      "moduleBackend": {{ .Values.moduleRegistryType | quote }},
      "moduleRegistry": {{ toJson .Values.moduleRegistry }}
    {{- end}}
    }
