apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  config.yaml: |
    registries:
{{ .Values.registries | toYaml | indent 6 }}
