apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  config: |
    {{- if eq "github" .Values.moduleRegistryType }}
    moduleRegistryType={{ .Values.moduleRegistryType | lower }}
    {{- end }}
