apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  config.json: |
    {{- if eq "github" .Values.moduleRegistryType }}
    {{ .Values.github | toJson | quote }}
    {{- end }}
