apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "hellas.labels" . | nindent 4 }}
  name: {{ include "hellas.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hellas.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "hellas.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/tls: {{ include (print $.Template.BasePath "/secret-tls.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hellas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageKey.repository }}:{{ .Values.imageKey.tag }}"
          imagePullPolicy: {{ .Values.imageKey.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: "/healthcheck"
              port: 8443
              scheme: HTTPS
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: "/healthcheck"
              port: 8443
              scheme: HTTPS
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: hellas
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: tls
              mountPath: "/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: {{ include "hellas.fullname" . }}-tls
        - name: config
          configMap:
            name: {{ include "hellas.fullname" . }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8}}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8}}
      {{- end }}
