apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  server.crt: {{ .Values.cert }}
  server.key: {{ .Values.key }}
