{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hellas.fullname" . }}
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  token: {{ .Values.github.token | b64enc -}}
{{- end }}
