apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "hellas.fullname" . }}-tls
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.cert }}
  tls.key: {{ .Values.key }}
