apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "hellas.labels" . | nindent 4 }}
  name: {{ include "hellas.fullname" . }}
spec:
  ports:
  - name: hellas
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "hellas.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
