apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "hellas.labels" . | nindent 4 }}
  name: {{ include "hellas.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hellas.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "hellas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.imageKey.repository }}:{{ .Values.imageKey.tag }}"
          imagePullPolicy: {{ .Values.imageKey.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: "/healthcheck"
              port: 8443
              scheme: HTTPS
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: "/healthcheck"
              port: 8443
              scheme: HTTPS
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8443
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8}}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8}}
      {{- end }}

