---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: terraform
  name: terraform
spec:
  containers:
  - command:
    - sleep
    - infinity
    env:
    - name: "TF_LOG"
      value: "TRACE"
    image: hashicorp/terraform:1.0.11
    name: terraform
    resources: {}
    volumeMounts:
    - name: apps
      mountPath: /app
    - name: terraform
      mountPath: /terraform
  volumes:
  - name: apps
    emptyDir: {}
  - name: terraform
    configMap:
      name: terraform

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform
data:
  main.tf: |
    module "hellas_vpc" {
      source  = "hellas.default/terraform-aws-modules/vpc/aws"
      version = "3.11.0"
      # insert the 21 required variables here
    }
