replicaCount: 1

moduleRegistryType: ""
cert: "Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOiAxICgweDEpCiAgICAgICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPWhlbGxhcy5oZWxsYXNAMTczMzAxMzY3MQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IERlYyAgMSAwMDo0MToxMSAyMDI0IEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBBcHIgMTggMDA6NDE6MTEgMjA1MiBHTVQKICAgICAgICBTdWJqZWN0OiBDTj1zZXJ2ZXIKICAgICAgICBTdWJqZWN0IFB1YmxpYyBLZXkgSW5mbzoKICAgICAgICAgICAgUHVibGljIEtleSBBbGdvcml0aG06IHJzYUVuY3J5cHRpb24KICAgICAgICAgICAgICAgIFB1YmxpYy1LZXk6ICgyMDQ4IGJpdCkKICAgICAgICAgICAgICAgIE1vZHVsdXM6CiAgICAgICAgICAgICAgICAgICAgMDA6ZDQ6OWM6MWU6NzA6MGY6ZGQ6NjQ6OWM6NmM6YTA6ZmY6ZTU6YmE6M2Q6CiAgICAgICAgICAgICAgICAgICAgOTU6OTQ6Njc6OTg6ODA6M2E6ODQ6YWM6YWU6N2M6YWE6MTk6NDI6NWY6ZGY6CiAgICAgICAgICAgICAgICAgICAgZGE6OTE6ODU6NDI6MTA6MmI6YTY6ZGI6YjU6MjU6NTQ6NzM6ZmY6MDc6Mjk6CiAgICAgICAgICAgICAgICAgICAgOTM6NzI6MjA6OGM6YjA6ZjU6NGM6NjU6Njk6YmI6MGE6ZDM6ODQ6ZDc6YTk6CiAgICAgICAgICAgICAgICAgICAgYTY6MWQ6OGI6NGY6YmQ6ODA6ZjU6ZDY6MjQ6MGI6Yzg6ZmY6ZmI6MWE6MjE6CiAgICAgICAgICAgICAgICAgICAgM2M6MGE6NDY6NjI6Zjc6NjU6NmE6OGQ6ZjI6YTA6Mjk6Zjk6NTE6ZGY6ZWE6CiAgICAgICAgICAgICAgICAgICAgMjc6OTg6NzI6OWY6ODA6Mjc6MmU6YzI6NDA6Yjk6OTQ6MTI6MTc6YjA6MDE6CiAgICAgICAgICAgICAgICAgICAgYWE6NTk6ODE6ZTQ6Yzg6OWY6ZDU6N2I6NWU6NDI6N2Y6ZGY6MmQ6ZjQ6YjI6CiAgICAgICAgICAgICAgICAgICAgOGY6ZTg6MTY6MDc6NTg6Y2Q6OGI6YWY6YzM6NGI6YjY6ODM6ZTM6MzU6MDU6CiAgICAgICAgICAgICAgICAgICAgZTI6NWI6NGU6NDI6MWY6MGQ6NTI6OGE6M2Y6NDM6Y2I6ZjM6ZDQ6NjQ6MDg6CiAgICAgICAgICAgICAgICAgICAgMzk6ZmQ6Y2E6NDQ6MjQ6NGY6ZmY6ZDQ6ZDI6OWI6ZGY6Nzc6ZWQ6YzU6NTE6CiAgICAgICAgICAgICAgICAgICAgNmY6YjM6ZDc6MzE6YmY6YWQ6ZTg6NDI6MTA6NTY6NGI6YjU6YTM6OWM6ODA6CiAgICAgICAgICAgICAgICAgICAgMTI6MDM6OTQ6ZTU6MDM6ZWU6YTE6ODk6N2U6ZmU6OTc6M2I6ZGY6MmY6NmQ6CiAgICAgICAgICAgICAgICAgICAgOGM6MWQ6YzI6ZjU6OWY6YzA6MWI6ODY6ZTE6M2Y6ZDc6OGQ6ZGY6MmI6Yjc6CiAgICAgICAgICAgICAgICAgICAgOWQ6OGY6ZjU6YzU6MDU6ZjY6Y2Y6ZjM6YWU6YzA6ZjQ6MTE6MTM6MGY6ZjE6CiAgICAgICAgICAgICAgICAgICAgNzE6NWY6Y2M6NTg6MzY6YmQ6MTE6MmM6YTQ6Njc6MzU6MDk6MWY6OGU6ZjE6CiAgICAgICAgICAgICAgICAgICAgYzQ6N2Q6YTI6N2Q6MDU6YjQ6NWE6OGM6NjA6NWU6ZTE6MjU6MWU6YmQ6Yzg6CiAgICAgICAgICAgICAgICAgICAgZTA6MjMKICAgICAgICAgICAgICAgIEV4cG9uZW50OiA2NTUzNyAoMHgxMDAwMSkKICAgICAgICBYNTA5djMgZXh0ZW5zaW9uczoKICAgICAgICAgICAgWDUwOXYzIEJhc2ljIENvbnN0cmFpbnRzOiAKICAgICAgICAgICAgICAgIENBOkZBTFNFCiAgICAgICAgICAgIFg1MDl2MyBTdWJqZWN0IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIEMxOjVFOjQ2OjU0OjZFOkVGOjNDOjlFOjQwOjVFOkI3OkY2OjAzOjIzOjgxOjg0Ojc3OjlGOkMwOjdCCiAgICAgICAgICAgIFg1MDl2MyBBdXRob3JpdHkgS2V5IElkZW50aWZpZXI6IAogICAgICAgICAgICAgICAga2V5aWQ6RUI6NUU6NUE6NUY6OEE6OTg6MzU6ODM6QjU6MEI6QzI6Njg6MTE6QkM6Mzc6RDA6OUU6Mzg6NTI6OUYKICAgICAgICAgICAgICAgIERpck5hbWU6L0NOPWhlbGxhcy5oZWxsYXNAMTczMzAxMzY3MQogICAgICAgICAgICAgICAgc2VyaWFsOjJBOjFEOjBEOjczOkNGOjkyOkEyOkEzOjRBOjlCOkE3OjI2Ojc5OkMyOjcxOkMwOkRGOjY2OjhGOjY4CiAgICAgICAgICAgIFg1MDl2MyBFeHRlbmRlZCBLZXkgVXNhZ2U6IAogICAgICAgICAgICAgICAgVExTIFdlYiBTZXJ2ZXIgQXV0aGVudGljYXRpb24KICAgICAgICAgICAgWDUwOXYzIEtleSBVc2FnZTogCiAgICAgICAgICAgICAgICBEaWdpdGFsIFNpZ25hdHVyZSwgS2V5IEVuY2lwaGVybWVudAogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBBbHRlcm5hdGl2ZSBOYW1lOiAKICAgICAgICAgICAgICAgIEROUzpoZWxsYXMuaGVsbGFzLCBETlM6aGVsbGFzLmhlbGxhcy5zdmMuY2x1c3Rlci5sb2NhbAogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgIFNpZ25hdHVyZSBWYWx1ZToKICAgICAgICA1Nzo5Nzo2MjpkZjpjOTozMzo0NzpmOTpjMDoyMTozNjo4ZDo5YToxYzozYzo5ODo3Njo2OToKICAgICAgICA3NTphZjozMzplNTpjYzo1ZjpjMzplYTpjMjo5NTpjNTo2MjphNjoyZTpiZDoyYTo1MTo0ODoKICAgICAgICA3MDo5Zjo0ZjoxYzpiNTo1OTplZjo1MDphYzplODowODo5YzphMzowZDowMzo2ZjoxMzpkMToKICAgICAgICA0ZTowMjo0Mjo3OTowMDo0NzpjMDo1MzoyNTo4Mzo4MzpiODoyNjpjZTpmNjo3NTowZDpjMjoKICAgICAgICA0NToyYTplMDo5Njo1ZDo0OToxZDpkYTplYTpjMjo2Zjo5Zjo1ZDo1ODo3MTpjOToyZjpjNToKICAgICAgICA3Mzo1MzowZDplYzo0YjpmYzpkMzpiYjowYjo3ZTowMjoxYTpiNTo0Mzo4OTpmOTpkNDoyMjoKICAgICAgICAwZDowNDo2Nzo4Yzo0MjpjNDoxZjoyMzo3Nzo5NDo3OToyODpjMjo5Njo0MjoxOTplODphOToKICAgICAgICBlMTo0OTphYTpkNDo2NDplYTo0YzpkOTo2MjphNDoxOTphZjo0Yjo3ZDo4MDoyNjplNDo2MjoKICAgICAgICAxNjoxYjozNDoxMzpjNzpmNDo3MDpmMToxYzoyNzphZjpmZTo5YTpkNjpmZToyYTo3Zjo0MDoKICAgICAgICBmZjpiNjphYjo5YTo3OTo0Mzo3MTpmNjo1MToyMTo0YTpjYzpjYTozNjoxZTo5ZjoyNDphODoKICAgICAgICA4OTo0MzpmMjpkYTpiZjo0YjplMDphNDoxNDoyNTo0Yzo3YzowZTpmZjphYTplNzoxOTpkYToKICAgICAgICBiMDpmMToxZjoyNjowMDo0ZTozZTpjMTpjZDo3MzoyMjpkZDozYTphNDpkMTo0YToxYTpkNzoKICAgICAgICAwZDpjYjowZjo3ODo3MDpiOToyMzo1NDowNDo1NTpkZjozYjozMToyZjo3YzpjYTplNDpmNDoKICAgICAgICAzMzowNDo1YjpjZToyMzo2OTpiNzpkMjo0NzpkZDoxMzplYjoyMTplYzowOTpkNjpjYTphMToKICAgICAgICA4NzpjMzo1ZjoxNgotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRG5EQ0NBb1NnQXdJQkFnSUJBVEFOQmdrcWhraUc5dzBCQVFzRkFEQWpNU0V3SHdZRFZRUUREQmhvWld4cwpZWE11YUdWc2JHRnpRREUzTXpNd01UTTJOekV3SUJjTk1qUXhNakF4TURBME1URXhXaGdQTWpBMU1qQTBNVGd3Ck1EUXhNVEZhTUJFeER6QU5CZ05WQkFNTUJuTmxjblpsY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU5TY0huQVAzV1NjYktELzVibzlsWlJubUlBNmhLeXVmS29aUWwvZjJwR0ZRaEFycHR1MQpKVlJ6L3djcGszSWdqTEQxVEdWcHV3clRoTmVwcGgyTFQ3MkE5ZFlrQzhqLyt4b2hQQXBHWXZkbGFvM3lvQ241ClVkL3FKNWh5bjRBbkxzSkF1WlFTRjdBQnFsbUI1TWlmMVh0ZVFuL2ZMZlN5aitnV0Ixak5pNi9EUzdhRDR6VUYKNGx0T1FoOE5Vb28vUTh2ejFHUUlPZjNLUkNSUC85VFNtOTkzN2NWUmI3UFhNYit0NkVJUVZrdTFvNXlBRWdPVQo1UVB1b1lsKy9wYzczeTl0akIzQzlaL0FHNGJoUDllTjN5dTNuWS8xeFFYMnovT3V3UFFSRXcveGNWL01XRGE5CkVTeWtaelVKSDQ3eHhIMmlmUVcwV294Z1h1RWxIcjNJNENNQ0F3RUFBYU9CNmpDQjV6QUpCZ05WSFJNRUFqQUEKTUIwR0ExVWREZ1FXQkJUQlhrWlVidTg4bmtCZXQvWURJNEdFZDUvQWV6QmVCZ05WSFNNRVZ6QlZnQlRyWGxwZgppcGcxZzdVTHdtZ1J2RGZRbmpoU242RW5wQ1V3SXpFaE1COEdBMVVFQXd3WWFHVnNiR0Z6TG1obGJHeGhjMEF4Ck56TXpNREV6TmpjeGdoUXFIUTF6ejVLaW8wcWJweVo1d25IQTMyYVBhREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFUQUxCZ05WSFE4RUJBTUNCYUF3T1FZRFZSMFJCREl3TUlJTmFHVnNiR0Z6TG1obGJHeGhjNElmYUdWcwpiR0Z6TG1obGJHeGhjeTV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClY1ZGkzOGt6Ui9uQUlUYU5taHc4bUhacGRhOHo1Y3hmdytyQ2xjVmlwaTY5S2xGSWNKOVBITFZaNzFDczZBaWMKb3cwRGJ4UFJUZ0pDZVFCSHdGTWxnNE80SnM3MmRRM0NSU3JnbGwxSkhkcnF3bStmWFZoeHlTL0ZjMU1ON0V2OAowN3NMZmdJYXRVT0orZFFpRFFSbmpFTEVIeU4zbEhrb3dwWkNHZWlwNFVtcTFHVHFUTmxpcEJtdlMzMkFKdVJpCkZoczBFOGYwY1BFY0o2LyttdGIrS245QS83YXJtbmxEY2ZaUklVck15alllbnlTb2lVUHkycjlMNEtRVUpVeDgKRHYrcTV4bmFzUEVmSmdCT1BzSE5jeUxkT3FUUlNoclhEY3NQZUhDNUkxUUVWZDg3TVM5OHl1VDBNd1JiemlOcAp0OUpIM1JQcklld0oxc3FoaDhOZkZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFVuQjV3RDkxa25HeWcKLytXNlBaV1VaNWlBT29Tc3JueXFHVUpmMzlxUmhVSVFLNmJidFNWVWMvOEhLWk55SUl5dzlVeGxhYnNLMDRUWApxYVlkaTArOWdQWFdKQXZJLy9zYUlUd0tSbUwzWldxTjhxQXArVkhmNmllWWNwK0FKeTdDUUxtVUVoZXdBYXBaCmdlVEluOVY3WGtKLzN5MzBzby9vRmdkWXpZdXZ3MHUyZytNMUJlSmJUa0lmRFZLS1AwUEw4OVJrQ0RuOXlrUWsKVC8vVTBwdmZkKzNGVVcrejF6Ry9yZWhDRUZaTHRhT2NnQklEbE9VRDdxR0pmdjZYTzk4dmJZd2R3dldmd0J1Rwo0VC9YamQ4cnQ1MlA5Y1VGOXMvenJzRDBFUk1QOFhGZnpGZzJ2UkVzcEdjMUNSK084Y1I5b24wRnRGcU1ZRjdoCkpSNjl5T0FqQWdNQkFBRUNnZ0VBRDFYaXozN05kTlExbjYxUVF1S1lvZmVRK3ByVFRCTmFsRTIxeWNMcCtlVE0KblpiN0lQamhlWm5UcU9RWS93L3ErMWxPTlRodSt6cHVQV2RwYWRNaWRzNzdySUpnR1Q1TVBKZkRicjJoKzM5UApYc1Z1bVJNalBUZjB1dHgxdGN3ekVBN3BjK0tVTTlLdG1MN2VUanhTZ285ZzA1Rmp1QXFUTW1YakNoeEFEdmJiCngyY3hFSGY2bEVOTXFWNTg4TDdzTXhHajk5cGNIV0VlRlp2QXJOOW1WcXJSOHQ5MFl4bzZEYjlGVStyYzJqRzUKOEtUeEFyaFR3ZytUYXM0bWkwNWoxbWtQUENkdE1KK2VJZVZ5Q3hwSlk3NFdHQ0ZlQXdWaU5wWTE5U28vcHFqQwpmOHorc2ZnYktadmJFREtETkUrb0YvTHorU0xrTE9IOGJsbVRZRVU3d1FLQmdRRHFDZ3J5QURpbkg3aGkwR1FxCjlLdzdJMDFhbUkvMDJGUjdOaFNsWCsrUjZQU0xjWDVrcklrZzhQS1FWZVpiM2V6RWlPWHpCT3lRb0hoSlE0eWUKNm5MN3VyVDk3M1Y1YkhrRGw3bGp5aE02U25LYTcrNUxIWWptQ1RQdCtBNE0zd0FzaWh3TS8vaDNCOVBIRER1Mgpua1ZTb0xOSzZKamF1QTZQWTgrQmNDd3R3UUtCZ1FEb2owL0FBYmpiZ25hQzlya1BPRXBuNUJONmx1VUJsWDZOCkNuazRHMEdWREN6NU1XZXhsRTg5VlZ5YytCT3BLRFdOcHdTK2RyRW1LZ295eHZ4UGNKWCtOZGZyM2RpNTdPTDAKdVQvSUJZMzRBL0s3QUpsS1A1MmFSZ1BWaExUQXhQWkw5angwMHpTa1RlWkwzNGtXOE55VnN1enhpYmtFLy9nRgp3TGlVWW92TzR3S0JnUUNXbFNXYnRZYStDUXZERUdBU3YyQjlvR1lwNzFWWWJVUldEbUxVVU5pODRjMU9WeFRDCnc3eHJaSHc5WC9lYWpqekQ2MjFBb3A5dklzQ2lLd00wVUpidzNwMkxjV0g5WVV5dmdoUzNYeEptQS9hZk45YnoKbjZvd2tDVkliTHpsalNuNGZsZzBDUklkeS94MzZxZ1ZCTnFIb253WnEzU0Y3Yno0aDNqQXlLSzBRUUtCZ0NmbwpIN2xGRW1Hb200bVJxT1B4dHVMcEFtYXc2ZzlCaGZ2UjVrYzRkaUtMZWxRd3BDaVcySm9md2NxMXp6bmh5bjdLClFFZ211Zk5nbDJ0ck5mU3p6eWxXTi8wampvTXBJVEQ1Y1BaejdZNjNycmxrT3VuQXpOeWlVeG9hc2FHNnFzRVMKT2dHYUZKaDFQYVdiY0R6ZGpCeXNIWGk5TjJDaVEvOUl1T1BOblV3ZEFvR0FlVW9KZ05qNDJSVnBTWXNMell2ZQp1RnVld1pzVHllR2dIQ3VFeFJ6WGp3V00va3BUcWpIQWlBNGFlTEVJNXI5N1VNK1VteUhLTU44eWd2VmJuNVFQCmJCa2c3Ykx5TTB1S2Y2MGZ0dWwwaVBNZzZDck1BTzdTZSs1TkZzMm9QQ1RvNEsvci9sSUx2VHYrcmJrcGNSUE8KWWhrT0I1Nmd2Um1XZE9oV3dGSGRHcTg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"

moduleRegistry:
  insecureSkipVerify: false
  protocol: https

imageKey:
  repository: hellas
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false
  minAvailable: 2

updateStrategy:
  {}
  # rollingUpdate:
  #   maxUnavailable: 1
  #   maxSurge: 1
  # type: RollingUpdate

nodeSelector: {}

tolerations:
  []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

affinity:
# # An example of preferred pod anti-affinity, weight is in the range 1-100
# podAntiAffinity:
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 100
#     podAffinityTerm:
#       labelSelector:
#         matchExpressions:
#         - key: app.kubernetes.io/name
#           operator: In
#           values:
#           - hellas
#         - key: app.kubernetes.io/instance
#           operator: In
#           values:
#           - hellas
#       topologyKey: kubernetes.io/hostname

# # An example of required pod anti-affinity
# podAntiAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#   - labelSelector:
#       matchExpressions:
#       - key: app.kubernetes.io/name
#         operator: In
#         values:
#         - hellas
#       - key: app.kubernetes.io/instance
#         operator: In
#         values:
#         - hellas
#     topologyKey: "kubernetes.io/hostname"
